name: jigsolitaire
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  vibration: ^3.1.8
  just_audio: ^0.10.6
  audio_session: ^0.2.4
  flutter_soloud: ^4.1.6

    #bloc
  flutter_bloc: ^9.1.0
  flutter_confetti: ^0.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/puzzles/campaign/
    - assets/images/puzzles/master_challenge/
    - assets/images/collections/
    - assets/images/
    - assets/audio/
    - assets/
